### ISSUE TITLE
Bug: JS related error in the News.js file | inclusion of inappropriate API key

### ISSUE THREAD

**Issue by CODEX108** [techcsispit/NewsApp#3]
### Issues I observed
- Due to some incorrect use of hooks/async calls there seems an issue while fetching data
- There is an issue with the API key as well. The response is as follows
 `{"status":"error","code":"apiKeyInvalid","message":"Your API key is invalid or incorrect. Check your key, or go to https://newsapi.org to create a free API key."}` 
![image](https://github.com/techcsispit/NewsApp/assets/82377810/f58fbae0-2f9d-4174-af64-8fc6489ca768)

**Comment by techcsispit** [comment]
Noted.

Can you investigate as to what seems to be causing this issue?

**Comment by CODEX108** [comment]
> Noted.
> 
> Can you investigate as to what seems to be causing this issue?

Yes sure will look into it
